import Navbar from "@/Component/shared/Navbar";
import "./globals.css";
import 'antd/dist/reset.css'; 
export const metadata = {
  title: "Relation IT",
  description: "Generated by Relation IT",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
