import Navbar from "@/Component/shared/Navbar";
import "./globals.css";
import "antd/dist/reset.css";
import Container from "@/Component/UI/Container";
export const metadata = {
  title: "Relation IT",
  description: "Generated by Relation IT",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Navbar />
          {children}
        </Container>
      </body>
    </html>
  );
}
